package com.littlefox.app.foxschool.api.enumerate

enum class RequestCode
{
    CODE_DEFAULT,
    CODE_VERSION,
    CODE_AUTH_ME,
    CODE_MAIN,
    CODE_PASSWORD_CHANGE,
    CODE_PASSWORD_CHANGE_NEXT,
    CODE_PASSWORD_CHANGE_KEEP,
    CODE_SCHOOL_LIST,
    CODE_LOGIN,
    CODE_AUTH_CONTENT_PLAY,
    CODE_SAVE_PLAY_CONTENTS_LOG,
    CODE_ADD_BOOKSHELF_CONTENTS,
    CODE_QUIZ_INFORMATION,
    CODE_SAVE_QUIZ_RECORD,
    CODE_DOWNLOAD_QUIZ_RESOURCE,
    CODE_STUDENT_HOMEWORK_CALENDAR,
    CODE_STUDENT_HOMEWORK_DETAIL_LIST,
    CODE_STUDENT_COMMENT_REGISTER,
    CODE_STUDENT_COMMENT_UPDATE,
    CODE_STUDENT_COMMENT_DELETE
}